from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name="home"),
    path("register",views.register,name="register"),
    path("login",views.login,name="login"),
    path("blog",views.BlogList.as_view(),name="blog"),
    path("blog_details/<int:pk>/",views.BlogDetail.as_view(),name="blog_details"),
    path("blog_grid/<int:pk>/",views.BlogGrid.as_view(),name="blog_grid"),
    path("candidate",views.candidate,name="candidate"),
    path("candidate_details",views.candidate_details,name="candidate_details"),
    path("checkout",views.checkout,name="checkout"),
    path("invoice",views.invoice,name="invoice"),
    path("payment_complete",views.payment_complete,name="payment_complete"),
    path("pricing",views.pricing,name="pricing"),
    path("dashboard_pricing",views.dashboard_pricing,name="dashboard_pricing"),
    path("employer_pricing",views.employer_pricing,name="employer_pricing"),
    path("contact",views.contact,name="contact"),
    path("faq",views.faq,name="faq"),
    path("dashboard/username", views.dashboard, name="dashboard"),
    path("alert", views.dashboard_alert, name="alert"),
    path("applied", views.dashboard_applied, name="applied"),
    path("bookmark",  views.dashboard_bookmark, name="bookmark"),
    path("dashboard_edit", views.dashboard_edit, name="dashboard_edit"),
    path("message/<int:id>/username", views.dashboard_message,name= "message"),
    path("edit_resume", views.edit_resume,name= "edit_resume"),
    path("employer", views.employer_dashboard, name="employer"),
    path("manage_candidate", views.employer_dashboard_candidate, name="manage_candidate"),
    path("edashboard_edit", views.employer_dashboard_edit, name="edashboard_edit"),
    path("manage_job", views.employer_dashboard_job, name="manage_job"),
    path("emessage", views.employer_dashboard_message, name="emessage"),
    path("post", views.employer_dashboard_post, name="post"),
    path("job_post", views.job_post, name="job_post"),
    path("details", views.employer_details, name="details"),
    path("listing", views.employer_listing, name="listing"),
    path("add_resume", views.add_resume, name="add_resume"),
    path("resume", views.resume, name="resume"),
    path("about_us",views.about_us,name="about_us"),
    path("error",views._404,name="error"),
    path("how_it_work",views.how,name="how_it_work"),
    path("terms",views.terms,name="terms"),
    path("project_detail",views.job_detail,name="project_detail"),
    path("project_list",views.job_listing,name="project_list"),
    path("job_listing_map",views.job_map,name="job_listing_map"),
    path("logout", views.userlogout, name="logout"),
    path("search", views.search, name="search"),


    ]